version: 2
updates:
  # Rust CLI
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # VS Code extension
  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
